### ISSUE TITLE
Bang Commands May Still Fail Silently

### ISSUE THREAD

**Issue by hakanensari** [benmyles/mongomatic#5]
Example: If I do an insert! on an invalid object, it will fail silently. My expectation (correct me if I'm wrong) is that the method would raise a Mongo::OperationError "if there are any problems."

Same goes for the other bang commands.

This possibly deserves some refactoring of the `return false` at the top of the non-bang commands. Perhaps you can check if `opts[:safe] == true` and then raise rather than return false.

**Comment by benmyles** [comment]
Bang methods weren't meant to raise on validation exceptions, only db failures (ie. if Mongo isn't able to perform the transaction). I just released 0.6.2 which let's you pass in a {:raise => true} option to insert/update/remove (or their bang equivalents) that will raise on validation errors (and a few other errors).
